name: Deploy app node com github actions

on:
push:
brnaches:
- main

jobs: 
build-and-deploy:
runs-on: ubuntu-latest 

steps:
- name: Clonar repositório
uses: actions/checkout@v3

- name: Configurar Docker Buildx
uses: docker/setupa-buildx-action@v3

- name: Build da imagem Docker
uses: docker build -t hello-word-node .

- name: Finalizar
uses: echo "Build concluído. Render detectará o push e fará o deploy automaticamente"